# 2. Tensor 张量操作

PyTorch 的核心数据结构，类似 NumPy 的 ndarray，但支持 GPU 加速。

In [1]:
import torch

print(f"PyTorch 版本: {torch.__version__}")
print(f"CUDA 可用: {torch.cuda.is_available()}")

PyTorch 版本: 2.6.0+cu126
CUDA 可用: True


## 2.1 创建张量

In [2]:
# 从 Python 列表创建
a = torch.tensor([1, 2, 3, 4, 5])
print(f"一维张量: {a}")
print(f"形状: {a.shape}, 数据类型: {a.dtype}")

一维张量: tensor([1, 2, 3, 4, 5])
形状: torch.Size([5]), 数据类型: torch.int64


In [3]:
# 从嵌套列表创建二维张量
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"二维张量:\n{b}")
print(f"形状: {b.shape}")

二维张量:
tensor([[1, 2, 3],
        [4, 5, 6]])
形状: torch.Size([2, 3])


In [4]:
# 从 NumPy 数组创建
import numpy as np

arr = np.array([10, 20, 30])
c = torch.from_numpy(arr)
print(f"NumPy → Tensor: {c}")
print(f"类型: {c.dtype}")

NumPy → Tensor: tensor([10, 20, 30])
类型: torch.int64


## 2.2 常用初始化方法

In [ ]:
# 全零、全一、单位矩阵
zeros = torch.zeros(3, 4)       # 3行4列全零
ones = torch.ones(2, 3)         # 2行3列全一
eye = torch.eye(4)              # 4x4 单位矩阵
print(f"全零:\n{zeros}\n")
print(f"全一:\n{ones}\n")
print(f"单位矩阵:\n{eye}")

In [ ]:
# 随机初始化（深度学习中最常用）
rand = torch.randn(3, 4)           # 标准正态分布（均值0，标准差1）
randint = torch.randint(0, 10, (3, 4))  # 0~9 的随机整数
print(f"正态分布随机:\n{rand}\n")
print(f"随机整数:\n{randint}")

In [ ]:
# 指定数据类型和设备
x = torch.tensor([1, 2, 3], dtype=torch.float32)  # 指定为 float32
print(f"指定 dtype: {x.dtype}")

y = torch.ones(2, 3).to('cuda')  # 放到 GPU 上
print(f"设备: {y.device}")

## 2.3 张量运算

In [ ]:
# 基本运算 — 逐元素操作
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(f"加法: {x + y}")
print(f"减法: {x - y}")
print(f"乘法（逐元素）: {x * y}")
print(f"除法: {x / y}")

In [ ]:
# 矩阵乘法 — 深度学习中非常核心的操作
A = torch.randn(2, 3)  # 2x3 矩阵
B = torch.randn(3, 4)  # 3x4 矩阵

C = A @ B              # 等价于 torch.matmul(A, B)
print(f"A 形状: {A.shape}")
print(f"B 形状: {B.shape}")
print(f"A @ B 形状: {C.shape}")  # 结果是 2x4

In [ ]:
# 形状操作
x = torch.arange(12)  # [0, 1, 2, ..., 11]
print(f"原始: {x}, 形状: {x.shape}")

r = x.reshape(3, 4)   # 改成 3行4列
print(f"reshape(3,4):\n{r}")

v = x.view(2, 6)      # view 和 reshape 类似，但共享内存
print(f"view(2,6):\n{v}")

In [ ]:
# squeeze 和 unsqueeze — 增减维度
x = torch.randn(1, 3, 1)  # 形状 (1, 3, 1)
print(f"原始: {x.shape}")

s = x.squeeze()            # 去掉所有大小为1的维度
print(f"squeeze: {s.shape}")

u = s.unsqueeze(0)         # 在第0维增加一个维度
print(f"unsqueeze(0): {u.shape}")

In [ ]:
# transpose 和 permute — 转置与维度重排
x = torch.randn(2, 3, 4)  # 3维张量
print(f"原始: {x.shape}")

t = x.transpose(0, 1)     # 交换第0维和第1维
print(f"transpose(0,1): {t.shape}")

p = x.permute(2, 0, 1)    # 按指定顺序重排所有维度
print(f"permute(2,0,1): {p.shape}")

In [ ]:
# 拼接与拆分
a = torch.ones(2, 3)
b = torch.zeros(2, 3)

cat = torch.cat([a, b], dim=0)   # 沿行方向拼接
print(f"cat (dim=0): {cat.shape}\n{cat}\n")

stack = torch.stack([a, b], dim=0)  # 新增一个维度堆叠
print(f"stack (dim=0): {stack.shape}\n{stack}\n")

chunks = torch.chunk(cat, 2, dim=0)    # 拆成2块
print(f"chunk 拆分结果: {[c.shape for c in chunks]}")

## 2.4 NumPy 互转与索引切片

### NumPy ↔ Tensor 互转

- `.numpy()` — Tensor → NumPy
- `torch.from_numpy()` — NumPy → Tensor
- **重要**：两者共享内存，修改一个另一个也会跟着变
- 只有 **CPU 上的 Tensor** 才能转 NumPy，GPU 上的需要先 `.cpu()`

### 索引与切片

- 和 Python 列表 / NumPy 的语法完全一致
- `[start:stop:step]` 基本格式
- 支持布尔索引和高级索引

In [19]:
# NumPy ↔ Tensor 互转
import numpy as np

# Tensor → NumPy
t = torch.tensor([1, 2, 3, 4, 5])
arr = t.numpy()
print(f"Tensor: {t}")
print(f"NumPy: {arr}")

# 共享内存验证：改一个另一个也会变
t[0] = 999
print(f"\n修改 Tensor 后 — Tensor: {t}, NumPy: {arr}")

Tensor: tensor([1, 2, 3, 4, 5])
NumPy: [1 2 3 4 5]

修改 Tensor 后 — Tensor: tensor([999,   2,   3,   4,   5]), NumPy: [999   2   3   4   5]


In [20]:
# GPU 上的 Tensor 需要先转到 CPU
gpu_tensor = torch.ones(3).to('cuda')
# gpu_tensor.numpy()  # 这行会报错！GPU 张量不能直接转 NumPy

arr = gpu_tensor.cpu().numpy()  # 先 .cpu() 再转
print(f"GPU → CPU → NumPy: {arr}")

GPU → CPU → NumPy: [1. 1. 1.]


In [21]:
# 基本索引和切片
x = torch.arange(10)  # [0, 1, 2, ..., 9]
print(f"原始: {x}")
print(f"x[0]: {x[0]}")          # 取第1个
print(f"x[-1]: {x[-1]}")        # 取最后一个
print(f"x[2:5]: {x[2:5]}")      # 切片，索引2到4
print(f"x[:3]: {x[:3]}")        # 前3个
print(f"x[::2]: {x[::2]}")      # 每隔一个取一个（步长为2）

原始: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[0]: 0
x[-1]: 9
x[2:5]: tensor([2, 3, 4])
x[:3]: tensor([0, 1, 2])
x[::2]: tensor([0, 2, 4, 6, 8])


In [22]:
# 二维张量索引
m = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"矩阵:\n{m}\n")
print(f"m[0]: {m[0]}")          # 第1行
print(f"m[0, 1]: {m[0, 1]}")    # 第1行第2列的元素
print(f"m[:, 0]: {m[:, 0]}")    # 所有行的第1列
print(f"m[0:2, 1:]:\n{m[0:2, 1:]}")  # 前2行，从第2列开始

矩阵:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

m[0]: tensor([1, 2, 3])
m[0, 1]: 2
m[:, 0]: tensor([1, 4, 7])
m[0:2, 1:]:
tensor([[2, 3],
        [5, 6]])


In [23]:
# 布尔索引 — 按条件筛选元素
x = torch.tensor([10, 5, 20, 3, 15, 8])

mask = x > 10          # 生成布尔掩码
print(f"mask: {mask}")
print(f"x[x > 10]: {x[mask]}")  # 筛选大于10的元素

# 实际应用：把负数置零（类似 ReLU 的效果）
y = torch.randn(5)
print(f"\n原始: {y}")
y[y < 0] = 0
print(f"负数置零: {y}")

mask: tensor([False, False,  True, False,  True, False])
x[x > 10]: tensor([20, 15])

原始: tensor([ 0.0513, -1.2393, -0.9253, -1.0813, -1.1177])
负数置零: tensor([0.0513, 0.0000, 0.0000, 0.0000, 0.0000])
